### ISSUE TITLE
Hololive tab

### ISSUE THREAD

**Issue by Smug00** [jogerj/place-atlas#19] opened 2022-04-05 03:01 UTC
{
	"id": 0,
	"name": "Hololive ",
	"description": "Hololive is a Vtuber Agency that is owned by Cover Corporation and Motoaki Tanigo (Yagoo) as it's CEO. Hololive consists of different branches which are divided to HoloJP, HoloEN, HoloID and hololive's male vtuber group Holostars. ",
	"website": "https://en.hololive.tv/",
	"subreddit": "/r/Hololive",
	"center": [
		1041.5,
		1986.5
	],
	"path": [
		[
			1031.5,
			1976.5
		],
		[
			1051.5,
			1976.5
		],
		[
			1051.5,
			1995.5
		],
		[
			1031.5,
			1995.5
		],
		[
			1031.5,
			1995.5
		]
	]
}

**Comment by jogerj** [comment] 2022-04-05 15:59
duplicate of r/placestart entry

**Closed as completed by jogerj** 2022-04-05 15:59 UTC
Labels: duplicate
