### ISSUE TITLE
FlareWheeze

### ISSUE THREAD

**Issue by Articucho** [jogerj/place-atlas#21] opened 2022-04-05 03:05 UTC
{
    	"id": 0,
    	"name": "FlareWheeze",
    	"description": "FlareWheeze is an emote based on the Vtuber named Shiranui Flare from Hololive production.",
    	"website": "https://en.hololive.tv/",
    	"subreddit": "/r/hololive",
    	"center": [
    		1385.5,
    		888.5
    	],
    	"path": [
    		[
    			1400.5,
    			901.5
    		],
    		[
    			1400.5,
    			900.5
    		],
    		[
    			1401.5,
    			900.5
    		],
    		[
    			1401.5,
    			897.5
    		],
    		[
    			1402.5,
    			897.5
    		],
    		[
    			1403.5,
    			897.5
    		],
    		[
    			1403.5,
    			894.5
    		],
    		[
    			1402.5,
    			894.5
    		],
    		[
    			1402.5,
    			893.5
    		],
    		[
    			1402.5,
    			892.5
    		],
    		[
    			1401.5,
    			892.5
    		],
    		[
    			1400.5,
    			892.5
    		],
    		[
    			1400.5,
    			890.5
    		],
    		[
    			1399.5,
    			890.5
    		],
    		[
    			1399.5,
    			888.5
    		],
    		[
    			1399.5,
    			887.5
    		],
    		[
    			1400.5,
    			887.5
    		],
    		[
    			1400.5,
    			886.5
    		],
    		[
    			1402.5,
    			886.5
    		],
    		[
    			1402.5,
    			883.5
    		],
    		[
    			1401.5,
    			883.5
    		],
    		[
    			1401.5,
    			884.5
    		],
    		[
    			1400.5,
    			884.5
    		],
    		[
    			1399.5,
    			884.5
    		],
    		[
    			1399.5,
    			882.5
    		],
    		[
    			1398.5,
    			882.5
    		],
    		[
    			1398.5,
    			880.5
    		],
    		[
    			1397.5,
    			880.5
    		],
    		[
    			1397.5,
    			878.5
    		],
    		[
    			1396.5,
    			878.5
    		],
    		[
    			1396.5,
    			875.5
    		],
    		[
    			1395.5,
    			875.5
    		],
    		[
    			1395.5,
    			874.5
    		],
    		[
    			1394.5,
    			874.5
    		],
    		[
    			1394.5,
    			873.5
    		],
    		[
    			1393.5,
    			873.5
    		],
    		[
    			1393.5,
    			872.5
    		],
    		[
    			1392.5,
    			872.5
    		],
    		[
    			1391.5,
    			872.5
    		],
    		[
    			1391.5,
    			871.5
    		],
    		[
    			1390.5,
    			871.5
    		],
    		[
    			1389.5,
    			871.5
    		],
    		[
    			1389.5,
    			870.5
    		],
    		[
    			1382.5,
    			870.5
    		],
    		[
    			1382.5,
    			871.5
    		],
    		[
    			1381.5,
    			871.5
    		],
    		[
    			1378.5,
    			871.5
    		],
    		[
    			1378.5,
    			872.5
    		],
    		[
    			1376.5,
    			872.5
    		],
    		[
    			1376.5,
    			873.5
    		],
    		[
    			1374.5,
    			873.5
    		],
    		[
    			1374.5,
    			874.5
    		],
    		[
    			1374.5,
    			875.5
    		],
    		[
    			1373.5,
    			875.5
    		],
    		[
    			1373.5,
    			876.5
    		],
    		[
    			1373.5,
    			878.5
    		],
    		[
    			1372.5,
    			878.5
    		],
    		[
    			1372.5,
    			879.5
    		],
    		[
    			1371.5,
    			879.5
    		],
    		[
    			1371.5,
    			880.5
    		],
    		[
    			1371.5,
    			880.5
    		],
    		[
    			1370.5,
    			880.5
    		],
    		[
    			1370.5,
    			882.5
    		],
    		[
    			1370.5,
    			883.5
    		],
    		[
    			1369.5,
    			883.5
    		],
    		[
    			1369.5,
    			884.5
    		],
    		[
    			1368.5,
    			884.5
    		],
    		[
    			1369.5,
    			884.5
    		],
    		[
    			1369.5,
    			885.5
    		],
    		[
    			1369.5,
    			891.5
    		],
    		[
    			1370.5,
    			891.5
    		],
    		[
    			1370.5,
    			892.5
    		],
    		[
    			1370.5,
    			893.5
    		],
    		[
    			1371.5,
    			893.5
    		],
    		[
    			1371.5,
    			894.5
    		],
    		[
    			1372.5,
    			894.5
    		],
    		[
    			1372.5,
    			895.5
    		],
    		[
    			1372.5,
    			898.5
    		],
    		[
    			1372.5,
    			898.5
    		],
    		[
    			1372.5,
    			899.5
    		],
    		[
    			1371.5,
    			899.5
    		],
    		[
    			1371.5,
    			904.5
    		],
    		[
    			1372.5,
    			904.5
    		],
    		[
    			1372.5,
    			907.5
    		],
    		[
    			1373.5,
    			907.5
    		],
    		[
    			1373.5,
    			908.5
    		],
    		[
    			1373.5,
    			909.5
    		],
    		[
    			1375.5,
    			909.5
    		],
    		[
    			1377.5,
    			909.5
    		],
    		[
    			1379.5,
    			909.5
    		],
    		[
    			1379.5,
    			908.5
    		],
    		[
    			1378.5,
    			908.5
    		],
    		[
    			1378.5,
    			908.5
    		],
    		[
    			1378.5,
    			905.5
    		],
    		[
    			1377.5,
    			905.5
    		],
    		[
    			1377.5,
    			904.5
    		],
    		[
    			1376.5,
    			904.5
    		],
    		[
    			1376.5,
    			902.5
    		],
    		[
    			1376.5,
    			902.5
    		],
    		[
    			1388.5,
    			902.5
    		],
    		[
    			1388.5,
    			902.5
    		],
    		[
    			1388.5,
    			901.5
    		],
    		[
    			1389.5,
    			901.5
    		],
    		[
    			1389.5,
    			900.5
    		],
    		[
    			1393.5,
    			900.5
    		],
    		[
    			1393.5,
    			901.5
    		],
    		[
    			1394.5,
    			901.5
    		],
    		[
    			1394.5,
    			902.5
    		],
    		[
    			1399.5,
    			902.5
    		],
    		[
    			1400.5,
    			902.5
    		],
    		[
    			1400.5,
    			900.5
    		]
    	]
    }

**Comment by jogerj** [comment] 2022-04-05 16:12
Duplicate of #11

**Closed as completed by jogerj** 2022-04-05 16:12 UTC
Labels: duplicate
